const PROTOCOL_ID = 0xAF;
const DATAGRAM_CODES = {
	RELIABLE_UDP_HELLO: 0x10,
	RELIABLE_UDP_ESTABLISH: 0x11,
	RELIABLE_UDP_DATA: 0x20,
	RELIABLE_UDP_RESEND_REQ: 0x30,
	RELIABLE_UDP_DATA_ACK: 0x40
};

module.exports = {DATAGRAM_CODES, PROTOCOL_ID};